import 'dart:io';

import 'package:flutter_test/flutter_test.dart';

/// Extracts every ```dart fence from a dartdoc comment.
///
/// Only `///` comments count: a fence inside a regular `//` comment or inside
/// string data is not documentation and is not our contract with readers.
List<String> extractSnippets(String source) {
  final snippets = <String>[];
  final buffer = <String>[];
  var inside = false;

  for (final raw in source.split('\n')) {
    final line = raw.trimLeft();
    if (!line.startsWith('///')) continue;
    final content = line.length > 3 ? line.substring(4) : '';

    if (content.trimRight() == '```dart') {
      inside = true;
      buffer.clear();
      continue;
    }
    if (inside && content.trimRight() == '```') {
      inside = false;
      snippets.add(buffer.join('\n'));
      continue;
    }
    if (inside) buffer.add(content);
  }
  return snippets;
}

void main() {
  test('extractSnippets picks up fenced dart blocks in doc comments', () {
    const source = '''
/// Doc.
///
/// ```dart
/// const answer = 42;
/// ```
class A {}
''';
    expect(extractSnippets(source), <String>['const answer = 42;']);
  });

  test('extractSnippets ignores fences outside doc comments', () {
    const source = '''
// ```dart
// const nope = 1;
// ```
class A {}
''';
    expect(extractSnippets(source), isEmpty);
  });

  test(
    'every dartdoc code sample in lib/ type-checks against the real API',
    () async {
      final sources = Directory('lib')
          .listSync(recursive: true)
          .whereType<File>()
          .where((f) => f.path.endsWith('.dart') && !f.path.endsWith('.g.dart'))
          .toList()
        ..sort((a, b) => a.path.compareTo(b.path));

      final harness = StringBuffer()
        ..writeln('// GENERATED BY test/docs/doc_snippets_test.dart — do not edit.')
        ..writeln('//')
        ..writeln('// Each dartdoc sample becomes one function body. Placeholders the')
        ..writeln('// reader is expected to substitute (`issues`, `_save`, a model type)')
        ..writeln('// resolve to nothing, and analysis_options.yaml next to this file')
        ..writeln('// silences exactly those diagnostics. Everything that touches the')
        ..writeln('// octo_ui API itself — parameter names, argument types, arity,')
        ..writeln('// missing required arguments — is still checked.')
        ..writeln("import 'package:flutter/material.dart';")
        ..writeln("import 'package:octo_ui/octo_ui.dart';");

      var index = 0;
      final origins = <int, String>{};
      for (final file in sources) {
        final snippets = extractSnippets(file.readAsStringSync());
        for (final snippet in snippets) {
          origins[index] = file.path;
          final body = snippet.trimRight();
          // A sample ending in a statement drops straight into the function
          // body. One ending in a bare expression (`OctoButton.label(…)`) needs
          // a statement context — and it may still be preceded by setup lines,
          // so only the trailing expression gets wrapped.
          final String statements;
          if (body.endsWith(';') || body.endsWith('}')) {
            statements = body;
          } else {
            final cut = body.lastIndexOf(';\n');
            final setup = cut >= 0 ? body.substring(0, cut + 1) : '';
            final expression = cut >= 0 ? body.substring(cut + 1) : body;
            statements = '$setup\nfinal Object? _ = $expression;';
          }
          harness
            ..writeln()
            ..writeln('// ${file.path}')
            // `async` so a sample may await; the body is still fully analyzed.
            ..writeln('Future<void> _sample$index() async {')
            ..writeln(statements)
            ..writeln('}');
          index++;
        }
      }

      expect(index, greaterThan(0), reason: 'no dartdoc samples found in lib/');

      final dir = Directory('.dart_tool/octo_doc_snippets')..createSync(recursive: true);
      // No `include:` — the samples are illustrative fragments, so the package's
      // lint set (strict-inference, avoid_dynamic_calls, …) would flag style, not
      // correctness. Only the diagnostics listed here are suppressed.
      File('${dir.path}/analysis_options.yaml').writeAsStringSync('''
analyzer:
  errors:
    undefined_identifier: ignore
    undefined_function: ignore
    undefined_class: ignore
    non_type_as_type_argument: ignore
    unused_local_variable: ignore
    unused_element: ignore
    # A sample generic over the reader's own model type (`OctoDataTable<Issue>`)
    # gives that type argument no definition, and member access on it then reads
    # as possibly-null. That is an artifact of the placeholder, not a defect in
    # the sample.
    unchecked_use_of_nullable_value: ignore
    # A `const` list of items built from a placeholder enum
    # (`Severity.high`) is not constant, because the placeholder has no
    # definition. Also an artifact, not a defect.
    invalid_constant: ignore
''');
      final harnessFile = File('${dir.path}/snippets.dart')..writeAsStringSync('$harness');

      final result = await Process.run('dart', <String>['analyze', harnessFile.path]);

      expect(
        result.exitCode,
        0,
        reason: 'A dartdoc sample does not compile against the current API.\n'
            'Samples came from:\n'
            '${origins.entries.map((e) => '  _sample${e.key} — ${e.value}').join('\n')}\n\n'
            '${result.stdout}${result.stderr}',
      );
    },
    timeout: const Timeout(Duration(minutes: 3)),
  );
}
